version: "0.2"
allowCompoundWords: true
ignorePaths:
  - "**/__pycache__/**"
  - "**/_meta/**"
  - "**/.*cache/**"
  - "**/.devenv/**"
  - "**/.editorconfig"
  - "**/.gitignore"
  - "**/.venv/**"
  - "**/uv.lock"
import:
  - https://cdn.jsdelivr.net/npm/@cspell/dict-de-de@4/cspell-ext.json
  - https://cdn.jsdelivr.net/npm/@cspell/dict-en_us@4/cspell-ext.json
dictionaries:
  - aws
  - bash
  - coding-compound-terms
  - companies
  - cryptocurrencies
  - de_DE
  - en_US
  - filetypes
  - fullstack
  - golang
  - lorem-ipsum
  - networking-terms
  - node
  - npm
  - public-licenses
  - python
  - python-common
  - software-tools
  - softwareTerms
ignoreWords:
  - acritical
  - activ
  - aerror
  - aexception
  - ainfo
  - aopen
  - awarning
  - awith
  - cachix
  - closefd
  - dhms
  - direnvrc
  - ebit
  - eibit
  - fspath
  - gibit
  - gnused
  - golangci
  - gopls
  - hujson
  - jnoortheen
  - kbit
  - kibit
  - mbit
  - mcls
  - mibit
  - mult
  - nixd
  - nixpkgs
  - norecursedirs
  - numtide
  - pbit
  - pibit
  - runonsave
  - sema
  - sntl
  - taplo
  - tbit
  - tibit
  - vfspath
words: []
