[project]
  description     = ""
  name            = "Arcanum"
  readme          = "README.md"
  requires-python = ">=3.13"
  version         = "2026.08.12"

  authors = [
    { email = "developer@blockmage.dev", name = "Blockmage Developers" },
  ]

  dependencies = [
    "anyio>=4.14.2",
    "msgspec[toml,yaml]>=0.21.1",
    "onepassword-sdk>=0.4.1",
    "python-dotenv>=1.2.2",
    "sniffio>=1.3.1",
    "structlog>=26.1.0",
    "typed-sentinels>=1.1.1",
  ]

[dependency-groups]
  dev = [
    "devtools>=0.12.2",
    "pyfakefs>=6.2.0",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
    "pytest>=9.1.1",
  ]

# ------------------------------- build system ---------------------------------
[build-system]
  build-backend = "hatchling.build"
  requires      = [ "hatchling" ]

[tool.hatch.metadata]
  allow-direct-references = true

[tool.hatch.build]
  dev-mode-dirs = [ ".", "src" ]

# ------------------------------- tool: coverage -------------------------------
[tool.coverage.report]
  skip_empty = "true"

  exclude_also = [
    "@abstractmethod",
    "\\.\\.\\.",
    "class .*\\bProtocol\\):",
    "def __repr__",
    "def __str__",
    "if TYPE_CHECKING:",
    "if __name__ == .__main__.:",
    "msg =.*",
    "raise AssertionError",
    "raise NotImplementedError",
  ]

[tool.coverage.html]
  directory = "_meta/reports/coverage/html"

[tool.coverage.json]
  output = "_meta/reports/coverage/json/coverage.json"

[tool.coverage.xml]
  output = "_meta/reports/coverage/xml/coverage.xml"

# -------------------------------- tool: pytest --------------------------------
[tool.pytest.ini_options]
  addopts = [
    "--cov-report=html",
    "--cov=arcanum",
    "--import-mode=importlib",
    "-s",
    "-vv",
  ]

  python_files = [ "test_*.py" ]
  testpaths    = [ "." ]

  norecursedirs = [
    ".devenv",
    ".direnv",
    ".git",
    ".venv",
    "data",
    "submodules",
  ]

# ---------------------------------- tool: uv ----------------------------------
[tool.uv]
  compile-bytecode = true
  managed          = true

  [tool.uv.pip]
    compile-bytecode = true

  [tool.uv.workspace]
    members = [  ]

  [tool.uv.sources]
